version: "3.8"
services:

  # This file must be used in addition to docker-compose.base.yml
  # ex:
  #     docker compose --file docker-compose.base.yml --file docker-compose.dev.yml up
 
  reverse-proxy:
    volumes:
      - ./reverse-proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 8000:8000 # Preserve default FastAPI port
