version: "3.8"
services:

  # This file is supposed to be used in addition to the base docker-compose.yml
  # ex:
  #     docker compose --file docker-compose.base.yml --file docker-compose.dev.yml up
  
  database:
    ports:
      - target: 5432  
        # published: 5432 # Not required
  
  api:
    ports:
      - target: 8000
        published: 8000

  frontend:
    build:
      context: ./frontend
      args:
        - API_BASE_URL=http://0.0.0.0:8000
    ports:
      - target: 3000
        published: 3000 # Public

