version: "3.8"
services:

  #=== Database ===#

  database:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  #=== API ===#

  api:
    container_name: api
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    ports:
      - 8000:8000

  #=== Frontend ===#
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    command: yarn dev
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
