version: "3.8"
services:

  # This file is supposed to be used in addition to the base docker-compose.yml
  # ex:
  #     docker compose --file docker-compose.base.yml --file docker-compose.dev.yml up
 
  reverse-proxy:
    ports:
      - 3000:80   # Preserve default Nextjs port
      - 8000:8000 # Preserve default FastAPI port
