version: "3.8"
services:

  # This file must be used in addition to docker-compose.base.yml
  # ex:
  #     docker compose --file docker-compose.base.yml --file docker-compose.dev.yml up
 
  reverse-proxy:
    volumes:
      - ./reverse-proxy/conf/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
    ports:
      - 80:80
      - 443:443
