version: "3.8"
services:

  # This file must be used in addition to docker-compose.base.yml
  # ex:
  #     docker compose --file docker-compose.base.yml --file docker-compose.dev.yml up
 
  reverse-proxy:
    volumes:
      - ./reverse-proxy/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/ssl.crt:/etc/nginx/ssl.crt:ro
      - ./reverse-proxy/ssl.key:/etc/nginx/ssl.key:ro
    ports:
      - 80:80
      - 443:443
